import type { PeerListing } from './listingsApi'

/** Same ids as `server/lib/demo-marketplace-seed.js` — showcase checkout stays disabled. */
const PREFIX = 'demo_pub_lst_'

const p1 = 'demo_prof_arbour_homes'
const p2 = 'demo_prof_hedge_studio'
const p3 = 'demo_prof_loft_lane'
const p4 = 'demo_prof_coast_line'
const p5 = 'demo_prof_studio_north'

const createdAt = 1_730_000_000_000
const updatedAt = 1_730_003_600_000

function mk(
  idSuffix: string,
  profileAuthorId: string,
  profileDisplayName: string,
  profileAvatar: string,
  title: string,
  description: string,
  priceCents: number,
  compareAtCents: number,
  imageUrl: string,
  keywords: string,
  category = 'furniture',
): PeerListing {
  return {
    id: `${PREFIX}${idSuffix}`,
    createdAt,
    updatedAt,
    sellerUserId: null,
    sellerEmail: null,
    profileAuthorId,
    profileDisplayName,
    profileAvatar,
    title,
    description,
    priceCents,
    compareAtCents,
    category,
    condition: 'good',
    keywords,
    locationLabel: 'Brisbane · demo',
    sku: category === 'furniture' ? `DEMO-FURN-${idSuffix}` : `DEMO-MKT-${idSuffix}`,
    acceptsOffers: true,
    fetchDelivery: true,
    sameDayDelivery: true,
    status: 'published',
    images: [{ url: imageUrl, sort: 0 }],
    saleMode: 'fixed',
    auctionEndsAt: null,
    reserveCents: 0,
    minBidIncrementCents: 50,
    auctionHighBidCents: 0,
    auctionHighBidderKey: null,
    auctionClosed: false,
    bids: [],
  }
}

/** Used when GET /api/listings returns nothing or fails (e.g. static preview, API down). */
export const MARKETPLACE_MOCK_PEER_LISTINGS: PeerListing[] = [
  mk(
    '1',
    p1,
    'ArbourHomes',
    '🪑',
    'Mid-century oak sideboard — 180cm',
    'Demo listing. Solid oak, soft-close drawers, light wear on corners. Same-day Fetch delivery promo.',
    42000,
    58900,
    'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=82',
    'sideboard, oak, mid century, storage, dining, furniture',
  ),
  mk(
    '2',
    p1,
    'ArbourHomes',
    '🪑',
    'Velvet 3-seat sofa — forest green',
    'Demo listing. Deep seat, removable cushions. Pet-free home. Same-day delivery available.',
    89000,
    129000,
    'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=82',
    'sofa, velvet, lounge, green, three seater, furniture',
  ),
  mk(
    '3',
    p2,
    'HedgeStudio',
    '🛋️',
    'Round oak dining table — seats 6',
    'Demo listing. Pedestal base, seats six comfortably. Light surface marks.',
    65000,
    0,
    'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=900&q=82',
    'dining table, oak, round, six seater, furniture',
  ),
  mk(
    '4',
    p3,
    'LoftLane',
    '🏠',
    'Ergonomic mesh office chair',
    'Demo listing. Lumbar support, adjustable arms. WFH upgrade.',
    18500,
    32900,
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=82',
    'office chair, ergonomic, mesh, desk, furniture',
  ),
  mk(
    '5',
    p4,
    'CoastlineCo',
    '🌿',
    'Walnut desk with cable tray',
    'Demo listing. Minimal scratch on top. Cable management built in.',
    32000,
    45900,
    'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=900&q=82',
    'desk, walnut, office, cable management, furniture',
  ),
  mk(
    '6',
    p5,
    'StudioNorth',
    '✨',
    'Queen upholstered bed frame + slats',
    'Demo listing. Linen-look fabric, no mattress. Easy disassembly.',
    27500,
    41000,
    'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=82',
    'bed frame, queen, upholstered, bedroom, furniture',
  ),
  mk(
    '7',
    p2,
    'HedgeStudio',
    '🛋️',
    'Rattan accent chair + ottoman set',
    'Demo listing. Natural rattan weave, indoor use. Ottoman nests under seat when not in use.',
    24500,
    35900,
    'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=900&q=82',
    'rattan, chair, ottoman, accent, lounge, furniture',
  ),
  mk(
    '8',
    p3,
    'LoftLane',
    '🏠',
    'Glass-top nesting coffee tables (set of 2)',
    'Demo listing. Smoked glass, black powder-coated legs. Minor finger marks on glass.',
    19800,
    0,
    'https://images.unsplash.com/photo-1618220179428-22790b461013?w=900&q=82',
    'coffee table, nesting, glass, living room, furniture',
  ),
  mk(
    '9',
    p4,
    'CoastlineCo',
    '🌿',
    'Teak outdoor bench — 150cm',
    'Demo listing. Weathered silver patina; structure solid. Great for patio or entry.',
    31000,
    44800,
    'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=82',
    'teak, bench, outdoor, patio, furniture',
  ),
  mk(
    '10',
    p1,
    'ArbourHomes',
    '🪑',
    'Vintage ladder-back dining chairs (set of 4)',
    'Demo listing. Mixed wood tones; one chair has a small repair on the stretcher.',
    22000,
    34000,
    'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=900&q=82',
    'dining chairs, ladder back, set of four, vintage, furniture',
  ),
  mk(
    '11',
    p3,
    'LoftLane',
    '🎧',
    'Wireless earbuds — charging case incl.',
    'Demo listing. Barely used; all tips included. Sanitized case.',
    8900,
    15900,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=82',
    'earbuds, wireless, bluetooth, headphones, charger, electronics',
    'electronics',
  ),
  mk(
    '12',
    p2,
    'HedgeStudio',
    '👟',
    'Sneakers size US 10 (lightly worn)',
    'Demo listing. Genuine box; soles have light wear. Ships same week.',
    12900,
    22900,
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&q=82',
    'sneakers, shoes, nike, trainers, mens, fashion',
    'fashion',
  ),
  mk(
    '13',
    p1,
    'ArbourHomes',
    '📇',
    'Sealed TCG booster bundles (mixed)',
    'Demo listing. Factory sealed sleeves; mix of releases from last season.',
    24900,
    34900,
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=900&q=82',
    'trading cards, tcg, collectible, booster, sealed, pokemon',
    'collectibles',
  ),
  mk(
    '14',
    p5,
    'StudioNorth',
    '📱',
    'MagSafe grip stand + braided cable bundle',
    'Demo listing. Grip rotates; cable 1 m. Fits most MagSafe-ready cases.',
    4500,
    8990,
    'https://images.unsplash.com/photo-1625948515291-aebe09d956ec?w=900&q=82',
    'magsafe, iphone, charger, grip, electronics, accessory',
    'electronics',
  ),
  mk(
    '15',
    p4,
    'CoastlineCo',
    '🧥',
    'Oversized windbreaker jacket — fits M/L',
    'Demo listing. Waterproof shell; cuffs clean. Stored smoke-free.',
    6200,
    11900,
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&q=82',
    'jacket, windbreaker, oversized, mens, outdoors, fashion',
    'fashion',
  ),
  mk(
    '16',
    p3,
    'LoftLane',
    '📦',
    'Moving boxes bundle — curb pickup',
    'Demo listing. Mostly medium/large flats; flattened where noted. Pickup ASAP.',
    0,
    0,
    'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=900&q=82',
    'moving boxes, cardboard, curb pickup, giveaway, clearance, freebie',
    'free',
  ),
]
