/** Server-side AUD prices for supply SKUs — must match client `src/lib/suppliesCatalog.ts`. */

/** @type {Record<string, number>} */
export const SUPPLY_SKU_PRICE_AUD = {
  SUPPLY_DRINK_SOFT_CASE: 42,
  SUPPLY_DRINK_SPARKLING_12: 28,
  SUPPLY_DRINK_SPORTS_6: 32,
  SUPPLY_DRINK_ICED_TEA_8: 26,
  SUPPLY_CLEAN_PRO_KIT: 48,
  SUPPLY_CLEAN_FLOOR_SYS: 72,
  SUPPLY_CLEAN_STICK_VAC: 118,
  SUPPLY_CLEAN_SPRAY_TRIO: 36,
  SUPPLY_CLEAN_MICRO_BULK: 34,
  SUPPLY_CLEAN_GLOVES_NITRILE: 28,
  SUPPLY_CLEAN_DEGREASE: 22,
  SUPPLY_CLEAN_TOILET_SYS: 31,
  SUPPLY_CLEAN_GLASS_PRO: 26,
  SUPPLY_CLEAN_ODOUR_NEUT: 19,
  SUPPLY_CLEAN_MOP_PADS_8: 24,
  SUPPLY_PACK_MOVE_KIT_S: 89,
  SUPPLY_PACK_FRAGILE: 56,
  SUPPLY_PACK_TAPE_KIT: 42,
  SUPPLY_PACK_PAD_BLANKET: 78,
  SUPPLY_PACK_WARDROBE_BOX: 64,
  SUPPLY_PACK_PAPER_10KG: 38,
  SUPPLY_PACK_STRETCH_WRAP: 29,
  SUPPLY_PACK_MARKER_SET: 16,
  SUPPLY_PACK_MATTRESS_BAG: 18,
  SUPPLY_FETCH_MATTRESS_BAG_D: 37,
  SUPPLY_FETCH_MATTRESS_BAG_Q: 43,
  SUPPLY_FETCH_MATTRESS_BAG_K: 47,
  SUPPLY_PACK_ROPE_TIE: 22,
  SUPPLY_PACK_BUBBLE_NARROW: 35,
  SUPPLY_PACK_UTILITY_BLADES: 12,
  SUPPLY_HOME_DESK_LAMP: 46,
  SUPPLY_HOME_KETTLE: 59,
  SUPPLY_HOME_BEDDING_Q: 92,
  SUPPLY_HOME_TOWEL_SET: 52,
  SUPPLY_HOME_UTENSIL_BLK: 64,
  SUPPLY_HOME_SAUCEPAN_SET: 118,
  SUPPLY_HOME_SHOWER_CURT: 36,
  SUPPLY_HOME_BATH_MAT: 34,
  SUPPLY_HOME_STORAGE_3: 44,
  SUPPLY_HOME_DINNER_START: 78,
  SUPPLY_HOME_LED_BULBS: 32,
  SUPPLY_HOME_PEDAL_BIN: 72,
  SUPPLY_KITCHEN_DISH_RACK: 54,
  SUPPLY_BED_PILLOW_PAIR: 68,
  SUPPLY_BED_BLACKOUT_PAIR: 112,
  SUPPLY_BATH_SOAP_SET: 28,
  SUPPLY_LIVING_THROW: 74,
  SUPPLY_LIVING_COASTERS_6: 22,
  SUPPLY_LAUNDRY_HAMPER: 48,
  SUPPLY_LAUNDRY_LIQUID_2L: 26,
  SUPPLY_LAUNDRY_HANGERS_30: 34,
  SUPPLY_LAUNDRY_AIRER: 42,
  SUPPLY_STORE_VAC_BAGS: 36,
  SUPPLY_STORE_FABRIC_CUBE_2: 32,
}

/**
 * @param {string} sku
 * @returns {number | undefined}
 */
export function getSupplySkuPriceAud(sku) {
  if (!sku || typeof sku !== 'string') return undefined
  return SUPPLY_SKU_PRICE_AUD[sku]
}
